asr_riva_node:
  ros__parameters:
    stt_mic_timeout: 10
    riva.url: jetson:50051
    stt_configs:
      start_history: 50
      start_threshold: -1
      stop_history: 3500
      stop_history_eou: 1500
      stop_threshold: 0.8
      stop_threshold_eou: 0.9
