emotions_bridge:
  ros__parameters:

      eyebrow_left_vert:
        pin: 0
        start_angle: 30 ##tested
        final_angle: 150  ##tested
        type: 'percentual'

        neutral: 90 #ok
        happy: 110 #ok
        sad: 70 #ok
        surprised: 150 #ok
        angry: 95 #ok
        suspicious: 115 #ok
        sleepy: 60 #


      eyebrow_right_vert: 
        pin: 3
        start_angle: 25 ##tested -> invertido
        final_angle: 150 ##tested  
        type: 'percentual'

        neutral: 105 #ok
        happy: 65 #ok 
        sad: 125 #ok
        surprised: 25 #ok
        angry: 90 #ok
        suspicious: 150 #ok
        sleepy: 135 #


      eyebrow_left_rot:
        pin: 4
        start_angle: 115 ##tested
        final_angle: 175 ##tested
        type: 'rawangle'
    
        neutral: 145
        happy: 120
        sad: 10
        surprised: 130
        angry: 100
        suspicious: 120
        sleepy: 125


      eyebrow_right_rot:
        pin: 7
        start_angle: 105 ##tested
        final_angle: 165 ##tested 
        type: 'rawangle'

        neutral: 135
        happy: 43
        sad: 170
        surprised: 35
        angry: 75
        suspicious: 80
        sleepy: 35


      eyelid_left: 
        pin: 8
        start_angle: 40 ##tested - invertido (quanto maior, mais fechado)
        final_angle: 140 ##tested
        type: 'percentual'
        blink_left: true
        blink_closed_angle: 140 # Novo: Ângulo para fechar no piscar

        neutral: 60 #60
        happy: 40 #ok
        sad: 90 #ok
        surprised: 40 #ok
        angry: 90 #ok
        suspicious: 90 #ok
        sleepy: 130 #ok


      eyelid_right:
        pin: 11
        start_angle: 35 ##tested (quanto maior, mais aberto)
        final_angle: 150 #tested 
        type: 'percentual'
        blink_right: true
        blink_closed_angle: 35 # Novo: Ângulo para fechar no piscar
        
        neutral: 130 #130
        happy: 150 #ok
        sad: 85 #ok
        surprised: 150 #ok
        angry: 85 #ok
        suspicious: 85 #ok
        sleepy: 55


      eyes_ver: 
        pin: 12
        start_angle: 50
        final_angle: 50
        type: 'percentual'

        neutral: 50
        happy: 50
        sad: 100
        surprised: 50 
        angry: 50
        suspicious: 50
        sleepy: 50


      eyes_hor:
        pin: 15
        start_angle: 140
        final_angle: 0
        type: 'percentual'

        neutral: 70
        happy: 70
        sad: 70
        surprised: 70 
        angry: 70
        suspicious: 70
        sleepy: 70


      jaw: 
        pin: 5
        start_angle: 5
        final_angle: 25
        type: 'percentual'

        neutral: 25
        happy: 25
        sad: 25
        surprised: 10
        angry: 25
        suspicious: 25
        sleepy: 25