speech_recognizer_node:
  ros__parameters:
    stt_configs:
      compute_type: "float32"
      spinner: False
      model: "distil-small.en"
      silero_sensitivity: 0.6
      device: "cpu"
      webrtc_sensitivity: 1
      post_speech_silence_duration: 1.2
      min_length_of_recording: 3.0
      min_gap_between_recordings: 0.0
      enable_realtime_transcription: False
      silero_deactivity_detection: True
      initial_prompt: "James Michael Robert John David William Richard Joseph Thomas Christopher Mary Patricia Jennifer Linda Elizabeth Barbara Susan Jessica Karen Sarah"
    stt_mic_timeout: 10
