speech_recognizer_node:
  ros__parameters:
    stt_configs:
      compute_type: "float32"
      spinner: False
      model: "distil-small.en"
      silero_sensitivity: 0.6
      device: "cpu"
      webrtc_sensitivity: 1
      post_speech_silence_duration: 3.2
      min_length_of_recording: 2.0
      min_gap_between_recordings: 0.2
      enable_realtime_transcription: False
      silero_deactivity_detection: True
      initial_prompt: "sandwich coke wine water pizza burguer"
    stt_mic_timeout: 5